Saifullin Ildar, lab 1, #1
calculation-methods/M8O-303B-21 pull request #32
Opened 2024-04-04 17:25 UTC by IldarkoS

Сделал первый пункт первой лабы, отчета еще нет

2024-04-05 09:58 UTC, pivovarov-mai requested changes
Последний коммит лишний. Вам не нужно вливать в вашу ветку ветку lab1. Вам достаточно ответвится от мастера или лаб1.

2024-04-07 08:44 UTC, IldarkoS commented
Добавил решение второго и третьего пункта первой лабы. отчета нет

2024-04-07 16:03 UTC, IldarkoS commented
Выполнил все пункты первой лабы, отчета еще нет

2024-04-08 06:53 UTC, pivovarov-mai requested changes
В вашем запросе вы удаляете работы двух одногруппников, пожалуйста, уберите лишние коммиты по удалению.

2024-04-08 07:01 UTC, IldarkoS commented
я не знаю, как это сделать. я запушил их лабы в свой репозиторий. можно сделать так, я сделаю мерж в ваш репозиторий, а потом удалю работы у себя

2024-04-10 06:15 UTC, pivovarov-mai commented
> upd: я посмотрел, их работы не удалены, они лежат в ветке lab1

если вы зальете свои изменения, то они удалятся из той ветки

2024-04-10 06:20 UTC, IldarkoS commented
я отменил удаления. что делать дальше?

2024-04-13 08:36 UTC, closed without merging