Ilya Belov: 1.1
calculation-methods/M8O-303B-21 pull request #45
Opened 2024-04-13 08:23 UTC by xtempleZ

первая часть первой лабы

2024-04-13 11:43 UTC, pivovarov-mai requested changes

2024-04-13 11:43 UTC, pivovarov-mai commented on README.md
> -   - название запроса сделать латиницей по следующему шаблону "Surname Name, lab 1, #1,...", где вместо многоточия пишутся номера задач, которые выполнены
Это не ваши правки. Как они здесь оказались?

2024-04-13 11:55 UTC, xtempleZ commented on README.md
> -   - название запроса сделать латиницей по следующему шаблону "Surname Name, lab 1, #1,...", где вместо многоточия пишутся номера задач, которые выполнены
Не понял Вас. Сделал все по инструкции

2024-04-14 05:34 UTC, pivovarov-mai commented on README.md
> -   - название запроса сделать латиницей по следующему шаблону "Surname Name, lab 1, #1,...", где вместо многоточия пишутся номера задач, которые выполнены
вы добавляете что-то в ветку lab1, значит и ответвляется должны от нее, иначе в вашу ветку попадут лишние коммиты

2024-04-14 05:51 UTC, xtempleZ commented on README.md
> -   - название запроса сделать латиницей по следующему шаблону "Surname Name, lab 1, #1,...", где вместо многоточия пишутся номера задач, которые выполнены
Спасибо! Исправим.

2024-04-14 06:06 UTC, closed without merging